export const GET_MOVIES = 'GET_MOVIES';
export const SELECT_MOVIE_ID = 'SELECT_MOVIE_ID';
export const SELECTED_MOVIE = 'SELECT_MOVIE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const GET_UNSORTED_MOVIES = 'GET_UNSORTED_MOVIES';
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
